[package]
name = "rovr-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "rovr"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap_complete.workspace = true
clap.workspace = true
rovr-config.workspace = true
rovr-protocol.workspace = true
rovr-types.workspace = true
serde_json.workspace = true
toml.workspace = true
