[package]
name = "rovr-core"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
rovr-types.workspace = true
rovr-config.workspace = true
rovr-layout.workspace = true
rovr-layout-plugin = { path = "../rovr-layout-plugin" }
tracing.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
thiserror.workspace = true
